name: 'snowflake_dbt_project'
version: '1.0.0'
profile: 'snowflake_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# -------------------------
# MODELS CONFIG
# -------------------------

models:
  snowflake_dbt_project:
    # Config indicated by + and applies to all files under models/example/
    # Bronze Layer (Raw ingestion)
    bronze:
      +materialized: table
      +schema: bronze
    # Silver Layer (Cleaned + transformed)
    silver:
      +schema: silver
      # Default (for most tables)
      +materialized: table

      # Override for specific models
      silver_orders:
        +materialized: incremental

      silver_order_items:
        +materialized: incremental

      silver_customers:
        +materialized: view

# -------------------------
# SNAPSHOTS CONFIG
# -------------------------
snapshots:
  snowflake_dbt_project:
    +target_schema: snapshots
